title: Avto renovatsia
destination: docs
# baseurl: "/Slavi"
baseurl: ""
url: ""
markdown: kramdown
plugins:
    - jekyll-feed
sass:
    style: compressed
defaults:
    -
     scope:
         path: ""
     values:
         author: "Gergana Tsirkova"
         layout: page
         lang: bg
         base-url: "/"
    -
     scope:
         path: en
     values:
         lang: en
         base-url: "/en/"
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs]
langs-value:
    bg: ""
    en: en
t:
    home:
        bg: "НАЧАЛО"
        en: "HOME"
    services:
        bg: "УСЛУГИ"
        en: "SERVICES"
    contact:
        bg: "КОНТАКТИ"
        en: "CONTACTS"

